// .src/App.jsx
import React, { useEffect, useState } from 'react';
import { CartProvider } from './hooks/useCart';
import { Header } from './components/Header';
import { Footer } from './components/Footer';
import { HomePage } from './pages/HomePage';
import { ShopPage } from './pages/ShopPage';
import { ProductDetailPage } from './pages/ProductDetailPage';
import { CartPage } from './pages/CartPage';
import { AboutPage } from './pages/AboutPage';

export default function App() {
  const [currentPage, setCurrentPage] = useState('home');
  const [selectedProduct, setSelectedProduct] = useState(null);

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [currentPage, selectedProduct]);

  const navigate = (page) => {
    setCurrentPage(page);
    if (page !== 'product') {
      setSelectedProduct(null);
    }
  };

  const handleProductClick = (product) => {
    setSelectedProduct(product);
    setCurrentPage('product');
  };

  const renderPage = () => {
    switch (currentPage) {
      case 'home':
        return (
          <HomePage
            onNavigate={navigate}
            onProductClick={handleProductClick}
          />
        );

      case 'shop':
        return <ShopPage onProductClick={handleProductClick} />;

      case 'product':
        return selectedProduct ? (
          <ProductDetailPage
            product={selectedProduct}
            onBack={() => navigate('shop')}
            onNavigate={navigate}
            onProductClick={handleProductClick}
          />
        ) : (
          <ShopPage onProductClick={handleProductClick} />
        );

      case 'cart':
        return <CartPage onNavigate={navigate} />;

      case 'about':
        return <AboutPage />;

      default:
        return (
          <HomePage
            onNavigate={navigate}
            onProductClick={handleProductClick}
          />
        );
    }
  };

  return (
    <CartProvider>
      <div className="min-h-screen flex flex-col bg-[#FFFCF9]">
        <Header currentPage={currentPage} onNavigate={navigate} />
        <main className="flex-grow">{renderPage()}</main>
        <Footer onNavigate={navigate} />
      </div>
    </CartProvider>
  );
}

// svelte-app/src/App.svelte
<script>
  import Header from './components/Header.svelte';
  import Footer from './components/Footer.svelte';
  import HomePage from './pages/HomePage.svelte';
  import ShopPage from './pages/ShopPage.svelte';
  import ProductDetailPage from './pages/ProductDetailPage.svelte';
  import CartPage from './pages/CartPage.svelte';
  import AboutPage from './pages/AboutPage.svelte';

  let currentPage = 'home';
  let selectedProduct = null;

  function navigate(page) {
    currentPage = page;
    if (page !== 'product') {
      selectedProduct = null;
    }
  }

  function handleProductClick(product) {
    selectedProduct = product;
    currentPage = 'product';
  }
</script>

<div class="min-h-screen flex flex-col bg-[#FFFCF9]">
  <Header {currentPage} on:navigate={(e) => navigate(e.detail)} />

  <main class="flex-grow">
    {#if currentPage === 'home'}
      <HomePage 
        on:navigate={(e) => navigate(e.detail)} 
        on:productClick={(e) => handleProductClick(e.detail)} 
      />
    {:else if currentPage === 'shop'}
      <ShopPage on:productClick={(e) => handleProductClick(e.detail)} />
    {:else if currentPage === 'product'}
      {#if selectedProduct}
        <ProductDetailPage 
          product={selectedProduct} 
          on:back={() => navigate('shop')} 
          on:navigate={(e) => navigate(e.detail)}
        />
      {:else}
        <ShopPage on:productClick={(e) => handleProductClick(e.detail)} />
      {/if}
    {:else if currentPage === 'cart'}
      <CartPage on:navigate={(e) => navigate(e.detail)} />
    {:else if currentPage === 'about'}
      <AboutPage />
    {:else}
      <HomePage 
        on:navigate={(e) => navigate(e.detail)} 
        on:productClick={(e) => handleProductClick(e.detail)} 
      />
    {/if}
  </main>

  <Footer on:navigate={(e) => navigate(e.detail)} />
</div>

<style>
  :global(*){
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }
</style>
