// .src/pages/AboutPage.jsx
import React from 'react';
import { motion } from 'framer-motion';
import { Award, PenTool, Hammer, Search, CheckCircle } from 'lucide-react';
import { AnimatedCounter } from '../components/AnimatedCounter';
export function AboutPage() {
  return (
    <div className="min-h-screen bg-[#FFFCF9]">
      {/* Hero */}
      <section className="relative py-32 bg-[#3D3229] text-white overflow-hidden">
        <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80')] bg-cover bg-center opacity-15" />
        <div className="absolute inset-0 bg-gradient-to-t from-[#3D3229] to-transparent" />

        <div className="relative max-w-7xl mx-auto px-4 text-center">
          <motion.h1
            initial={{
              opacity: 0,
              y: 30
            }}
            animate={{
              opacity: 1,
              y: 0
            }}
            transition={{
              duration: 0.8
            }}
            className="text-5xl md:text-7xl font-bold tracking-tight mb-6">

            THE ART OF PRECISION
          </motion.h1>
          <motion.p
            initial={{
              opacity: 0,
              y: 20
            }}
            animate={{
              opacity: 1,
              y: 0
            }}
            transition={{
              duration: 0.8,
              delay: 0.2
            }}
            className="text-xl text-[#C9BDB0] max-w-2xl mx-auto font-light">

            We don't just design jewelry. We engineer it.
          </motion.p>
        </div>
      </section>

      {/* Story */}
      <section className="py-24 px-4 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-16 items-center">
          <div>
            <h2 className="text-3xl font-bold text-[#3D3229] mb-6">
              FOUNDED ON GEOMETRY
            </h2>
            <div className="text-[#6B5D50]">
              <p className="mb-4 leading-relaxed">
                Meridian was established with a singular vision: to translate
                the principles of modern architecture into wearable forms. We
                believe that structure is beautiful, and that precision is the
                ultimate luxury.
              </p>
              <p className="leading-relaxed">
                Unlike traditional jewelry houses that focus on ornamentation,
                we focus on form, balance, and material integrity. Every curve
                is calculated, every angle is intentional, and every piece is a
                study in proportion.
              </p>
            </div>
          </div>
          <div className="relative aspect-square bg-[#EDE7E0] p-8">
            <div className="absolute inset-0 border border-[#DDD5CC] m-4" />
            <div className="absolute inset-0 border border-[#DDD5CC] m-8 rotate-3" />
            <div className="w-full h-full bg-[#DDD5CC] flex items-center justify-center">
              <span className="text-[#B8A99A] font-mono text-sm tracking-widest">
                ARCHITECTURAL_FORM_01
              </span>
            </div>
          </div>
        </div>
      </section>

      {/* Process */}
      <section className="py-24 bg-[#EDE7E0] border-y border-[#DDD5CC]">
        <div className="max-w-7xl mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-[#3D3229] mb-4">
              OUR PROCESS
            </h2>
            <p className="text-[#8B7D6B]">From blueprint to brilliance.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            {[
            {
              icon: PenTool,
              title: 'Design',
              desc: 'CAD modeling with micron-level precision.'
            },
            {
              icon: Hammer,
              title: 'Cast',
              desc: 'Lost-wax casting in premium alloys.'
            },
            {
              icon: Search,
              title: 'Inspect',
              desc: 'Rigorous structural integrity testing.'
            },
            {
              icon: CheckCircle,
              title: 'Finish',
              desc: 'Hand-polishing to a mirror finish.'
            }].
            map((step, idx) =>
            <div
              key={step.title}
              className="bg-[#FFFCF9] p-8 border border-[#DDD5CC] text-center group hover:shadow-lg transition-shadow duration-300">

                <div className="w-16 h-16 bg-[#F5F0EB] rounded-full flex items-center justify-center mx-auto mb-6 group-hover:bg-[#3D3229] group-hover:text-white transition-colors duration-300">
                  <step.icon size={28} />
                </div>
                <h3 className="text-xl font-bold text-[#3D3229] mb-2">
                  {step.title}
                </h3>
                <p className="text-[#8B7D6B] text-sm">{step.desc}</p>
              </div>
            )}
          </div>
        </div>
      </section>

      {/* Stats */}
      <section className="py-24 px-4 max-w-7xl mx-auto border-b border-[#DDD5CC]">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 md:gap-0">
          <AnimatedCounter value={47} label="Years of Craft" />
          <AnimatedCounter value={12400} label="Pieces Created" suffix="+" />
          <AnimatedCounter value={23} label="Master Artisans" />
          <AnimatedCounter value={38} label="Countries Served" />
        </div>
      </section>

      {/* Certifications */}
      <section className="py-24 px-4 max-w-7xl mx-auto text-center">
        <h2 className="text-2xl font-bold text-[#3D3229] mb-12">
          CERTIFIED EXCELLENCE
        </h2>
        <div className="flex flex-wrap justify-center gap-8 md:gap-16">
          {[
          'GIA Certified',
          'Responsible Jewellery Council',
          'Fairmined Gold',
          'ISO 9001'].
          map((cert) =>
          <div key={cert} className="flex flex-col items-center">
              <div className="w-20 h-20 border-2 border-[#C9BDB0] rounded-full flex items-center justify-center mb-4">
                <Award className="text-[#B8A99A]" size={32} />
              </div>
              <span className="text-sm font-medium text-[#6B5D50]">{cert}</span>
            </div>
          )}
        </div>
      </section>
    </div>);

}

// svelte-app/src/pages/AboutPage.svelte
<script>
  import { Diamond, ShieldCheck, Ruler, Fingerprint } from 'lucide-svelte';
  import { fade, fly } from 'svelte/transition';
  import AnimatedCounter from '../components/AnimatedCounter.svelte';
</script>

<div class="min-h-screen bg-[#FFFCF9] pb-24" in:fade>
  <!-- Hero -->
  <section class="h-[60vh] bg-[#3D3229] relative overflow-hidden flex flex-col justify-center px-4">
    <div class="absolute inset-0 z-0 opacity-10">
      <div class="w-full h-full border-[100px] border-white rounded-full scale-110 transform translate-x-1/2 -translate-y-1/2 absolute top-0 right-0" />
    </div>
    
    <div class="max-w-7xl mx-auto w-full z-10 space-y-6">
      <h1 class="text-xs font-bold text-[#8B7D6B] tracking-[0.4em] uppercase">The House</h1>
      <h2 class="text-5xl md:text-8xl font-bold text-white leading-tight tracking-tight">Geometry & <br/>Heritage</h2>
    </div>
  </section>

  <!-- Content -->
  <section class="max-w-7xl mx-auto px-4 py-32 grid grid-cols-1 lg:grid-cols-2 gap-24">
    <div class="space-y-12">
      <div class="w-16 h-1 bg-[#3D3229]" />
      <h3 class="text-4xl font-bold text-[#3D3229] leading-tight">Founded on the intersection of modern architecture and manual craftsmanship.</h3>
      <p class="text-[#6B5D50] text-xl font-medium leading-relaxed">
        Meridian began as a studio dedicated to the study of form. We believe that jewelry should be an extension of the body's natural geometry, not an ornament.
      </p>
      <p class="text-[#8B7D6B] text-lg leading-relaxed">
        Our designs are influenced by brutalist structures, mathematical constants, and the golden ratio. Each piece is not just made; it is engineered using 3D modeling and hand-finished by master goldsmiths.
      </p>
    </div>
    
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-8">
      <div class="p-8 bg-[#F5F0EB] text-center space-y-4 border border-[#DDD5CC]">
        <div class="mx-auto w-12 h-12 flex items-center justify-center text-[#3D3229]">
          <ShieldCheck size={32} />
        </div>
        <h4 class="font-bold text-[#3D3229] uppercase tracking-widest text-sm">Authenticity</h4>
        <p class="text-xs text-[#8B7D6B] leading-relaxed font-medium">Every piece is laser-engraved with a unique serial number and digital certificate of ownership.</p>
      </div>
      <div class="p-8 bg-[#F5F0EB] text-center space-y-4 border border-[#DDD5CC]">
        <div class="mx-auto w-12 h-12 flex items-center justify-center text-[#3D3229]">
          <Ruler size={32} />
        </div>
        <h4 class="font-bold text-[#3D3229] uppercase tracking-widest text-sm">Precision</h4>
        <p class="text-xs text-[#8B7D6B] leading-relaxed font-medium">Tolerance levels of less than 0.01mm ensure perfect structural integrity across the collection.</p>
      </div>
      <div class="p-8 bg-[#F5F0EB] text-center space-y-4 border border-[#DDD5CC]">
        <div class="mx-auto w-12 h-12 flex items-center justify-center text-[#3D3229]">
          <Fingerprint size={32} />
        </div>
        <h4 class="font-bold text-[#3D3229] uppercase tracking-widest text-sm">Finishing</h4>
        <p class="text-xs text-[#8B7D6B] leading-relaxed font-medium">Seven stages of hand-polishing and ultrasonic cleaning for an unparalleled interior feel.</p>
      </div>
       <div class="p-8 bg-[#F5F0EB] text-center space-y-4 border border-[#DDD5CC]">
        <div class="mx-auto w-12 h-12 flex items-center justify-center text-[#3D3229]">
          <Diamond size={32} />
        </div>
        <h4 class="font-bold text-[#3D3229] uppercase tracking-widest text-sm">Rarity</h4>
        <p class="text-xs text-[#8B7D6B] leading-relaxed font-medium">Limited production batches ensure that each Meridian piece remains a rare artifact.</p>
      </div>
    </div>
  </section>

  <!-- Stats Section -->
  <section class="max-w-7xl mx-auto px-4 pb-32">
    <div class="grid grid-cols-2 md:grid-cols-4 gap-8 py-16 border-t border-[#EDE7E0]">
      <AnimatedCounter value={2018} label="Established" />
      <AnimatedCounter value={12000} label="Commissions" suffix="+" />
      <AnimatedCounter value={42} label="Countries" />
      <AnimatedCounter value={100} label="Satisfaction" suffix="%" />
    </div>
  </section>
</div>
